name: 'Close stale PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  stale:
    runs-on: github-ubuntu-latest-s
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10
        with:
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity. If there is no activity in the next 7 days it will be closed automatically'
          stale-pr-label: 'stale'
          days-before-stale: 7
          days-before-close: 7
          exempt-pr-labels: 'do-not-close,External Contribution'
