name: Unified Dogfooding scans
on:
  schedule:
    - cron: '45 3 * * *' # Run the workflow every day at 03:45 UTC
  workflow_dispatch:

jobs:
  unified-platform-dogfooding:
    runs-on: github-ubuntu-latest-s
    name: Unified Platform Dogfooding
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: SonarSource/ci-github-actions/build-gradle@v1
        with:
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          deploy-pull-request: false
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "org.sonarsource.jacoco:sonar-jacoco"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.jacoco:sonar-jacoco"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.jacoco:sonar-jacoco"
          shadow2_platform: "SQC-US"
